using backend.Domain.Enums;

namespace backend.Domain.Events;

/// <summary>
/// Domain event for when a biography has been generated by AI.
/// </summary>
public class BiographyGeneratedEvent : BaseEvent
{
    public Guid BiographyId { get; }
    public Guid MemberId { get; }
    public BiographyStyle Style { get; }
    public AIProviderType Provider { get; }
    public int TokensUsed { get; }
    public string UserPrompt { get; }

    public BiographyGeneratedEvent(Guid biographyId, Guid memberId, BiographyStyle style, AIProviderType provider, int tokensUsed, string userPrompt)
    {
        BiographyId = biographyId;
        MemberId = memberId;
        Style = style;
        Provider = provider;
        TokensUsed = tokensUsed;
        UserPrompt = userPrompt;
    }
}
