using backend.Application.AI.Common;
using backend.Application.Common.Interfaces;
using backend.Application.Common.Models;
using backend.Domain.Enums;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace backend.Infrastructure.AI;

public class GeminiAIContentGenerator : IAIContentGenerator
{
    private readonly ILogger<GeminiAIContentGenerator> _logger;
    private readonly AIConfig _aiConfig;

    public AIProviderType ProviderType => AIProviderType.Gemini;

    public GeminiAIContentGenerator(ILogger<GeminiAIContentGenerator> logger, IOptions<AIConfig> aiConfig)
    {
        _logger = logger;
        _aiConfig = aiConfig.Value;
    }

    public async Task<Result<AIResult>> GenerateContentAsync(AIRequest request, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(_aiConfig.Gemini?.ApiKey))
        {
            return Result<AIResult>.Failure("Gemini API Key is not configured.", "ConfigurationError");
        }

        // TODO: Implement actual call to Gemini API
        _logger.LogInformation("Generating content with Gemini for member {MemberId} and style {Style}.", request.MemberId, request.Style);

        // Simulate API call
        await Task.Delay(500, cancellationToken);

        var generatedContent = $"This is a simulated biography for member {request.MemberId} in {request.Style} style, generated by Gemini. Prompt: {request.UserPrompt}";
        var tokensUsed = request.UserPrompt.Length / 4 + generatedContent.Length / 4; // Very rough token estimation

        return Result<AIResult>.Success(new AIResult
        {
            Content = generatedContent,
            TokensUsed = tokensUsed,
            Provider = AIProviderType.Gemini,
            GeneratedAt = DateTime.UtcNow
        });
    }
}
