using backend.Application.AI.Common;
using backend.Application.Common.Interfaces;
using backend.Application.Common.Models;
using backend.Domain.Enums;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace backend.Infrastructure.AI;

public class OpenAIAIContentGenerator : IAIContentGenerator
{
    private readonly ILogger<OpenAIAIContentGenerator> _logger;
    private readonly AIConfig _aiConfig;

    public AIProviderType ProviderType => AIProviderType.OpenAI;

    public OpenAIAIContentGenerator(ILogger<OpenAIAIContentGenerator> logger, IOptions<AIConfig> aiConfig)
    {
        _logger = logger;
        _aiConfig = aiConfig.Value;
    }

    public async Task<Result<AIResult>> GenerateContentAsync(AIRequest request, CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrEmpty(_aiConfig.OpenAI?.ApiKey))
        {
            return Result<AIResult>.Failure("OpenAI API Key is not configured.", "ConfigurationError");
        }

        // TODO: Implement actual call to OpenAI API
        _logger.LogInformation("Generating content with OpenAI for member {MemberId} and style {Style}.", request.MemberId, request.Style);

        // Simulate API call
        await Task.Delay(700, cancellationToken);

        var generatedContent = $"This is a simulated biography for member {request.MemberId} in {request.Style} style, generated by OpenAI. Prompt: {request.UserPrompt}";
        var tokensUsed = request.UserPrompt.Length / 3 + generatedContent.Length / 3; // Very rough token estimation

        return Result<AIResult>.Success(new AIResult
        {
            Content = generatedContent,
            TokensUsed = tokensUsed,
            Provider = AIProviderType.OpenAI,
            GeneratedAt = DateTime.UtcNow
        });
    }
}
