using backend.Application.Common.Interfaces;
using backend.Application.Common.Models;
using backend.Domain.Entities;
using MediatR;
using Microsoft.Extensions.Logging;
using System.Threading;
using System.Threading.Tasks;
using backend.Domain.ValueObjects; // For BoundingBox
using backend.Application.Common.Constants;

namespace backend.Application.MemberFaces.Commands.CreateMemberFace;

public class CreateMemberFaceCommandHandler : IRequestHandler<CreateMemberFaceCommand, Result<Guid>>
{
    private readonly IApplicationDbContext _context;
    private readonly IAuthorizationService _authorizationService;
    private readonly ILogger<CreateMemberFaceCommandHandler> _logger;

    public CreateMemberFaceCommandHandler(IApplicationDbContext context, IAuthorizationService authorizationService, ILogger<CreateMemberFaceCommandHandler> logger)
    {
        _context = context;
        _authorizationService = authorizationService;
        _logger = logger;
    }

    public async Task<Result<Guid>> Handle(CreateMemberFaceCommand request, CancellationToken cancellationToken)
    {
        // 1. Authorize
        // Assuming authorization based on MemberId and FamilyId related to the member.
        // For simplicity, let's assume we need to get the FamilyId from the Member.
        var member = await _context.Members.FindAsync(new object[] { request.MemberId }, cancellationToken);
        if (member == null)
        {
            return Result<Guid>.Failure($"Member with ID {request.MemberId} not found.", ErrorSources.NotFound);
        }

        // We need to check if the user can access this family.
        // The CreateMemberFaceCommand doesn't directly provide FamilyId, so we get it from the member.
        if (!_authorizationService.CanAccessFamily(member.FamilyId))
        {
            return Result<Guid>.Failure(ErrorMessages.AccessDenied, ErrorSources.Forbidden);
        }

        // 2. Create MemberFace entity
        var entity = new MemberFace
        {
            MemberId = request.MemberId,
            FaceId = request.FaceId,
            BoundingBox = new BoundingBox {
                X = request.BoundingBox.X,
                Y = request.BoundingBox.Y,
                Width = request.BoundingBox.Width,
                Height = request.BoundingBox.Height
            },
            Confidence = request.Confidence,
            ThumbnailUrl = request.ThumbnailUrl,
            OriginalImageUrl = request.OriginalImageUrl,
            Embedding = request.Embedding,
            Emotion = request.Emotion,
            EmotionConfidence = request.EmotionConfidence ?? 0.0,
            IsVectorDbSynced = request.IsVectorDbSynced,
            VectorDbId = null // VectorDbId is generated by external service, not directly set on creation
        };

        _context.MemberFaces.Add(entity);

        await _context.SaveChangesAsync(cancellationToken);

        _logger.LogInformation("Created MemberFace {MemberFaceId} for Member {MemberId}.", entity.Id, request.MemberId);

        return Result<Guid>.Success(entity.Id);
    }
}
