// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Infrastructure.Data;

#nullable disable

namespace backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105111628_AddMemoryItemRefTypeAndLocationLinkLogic")]
    partial class AddMemoryItemRefTypeAndLocationLinkLogic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("backend.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("CalendarType")
                        .HasColumnType("int")
                        .HasColumnName("calendar_type");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid?>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("RepeatRule")
                        .HasColumnType("int")
                        .HasColumnName("repeat_rule");

                    b.Property<DateTime?>("SolarDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("solar_date");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_events_code");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_events_family_id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.EventMember", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("char(36)")
                        .HasColumnName("event_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.HasKey("EventId", "MemberId")
                        .HasName("pk_event_members");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_event_members_member_id");

                    b.ToTable("event_members");
                });

            modelBuilder.Entity("backend.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("TotalGenerations")
                        .HasColumnType("int")
                        .HasColumnName("total_generations");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("int")
                        .HasColumnName("total_members");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_families");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_families_code");

                    b.ToTable("families");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyDict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("char(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Lineage")
                        .HasColumnType("int")
                        .HasColumnName("lineage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("NamesByRegion")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("names_by_region");

                    b.Property<bool>("SpecialRelation")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("special_relation");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_family_dicts");

                    b.ToTable("family_dicts");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyLimitConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AiChatMonthlyLimit")
                        .HasColumnType("int")
                        .HasColumnName("ai_chat_monthly_limit");

                    b.Property<int>("AiChatMonthlyUsage")
                        .HasColumnType("int")
                        .HasColumnName("ai_chat_monthly_usage");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("MaxMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(50)
                        .HasColumnName("max_members");

                    b.Property<int>("MaxStorageMb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1024)
                        .HasColumnName("max_storage_mb");

                    b.HasKey("Id")
                        .HasName("pk_family_limit_configurations");

                    b.HasIndex("FamilyId")
                        .IsUnique()
                        .HasDatabaseName("ix_family_limit_configurations_family_id");

                    b.ToTable("family_limit_configurations");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("Family1Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("family1_id");

                    b.Property<Guid>("Family2Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("family2_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<DateTime>("LinkDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("link_date");

                    b.HasKey("Id")
                        .HasName("pk_family_links");

                    b.HasIndex("Family2Id")
                        .HasDatabaseName("ix_family_links_family2_id");

                    b.HasIndex("Family1Id", "Family2Id")
                        .IsUnique()
                        .HasDatabaseName("ix_family_links_family1_id_family2_id");

                    b.ToTable("family_links");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.HasKey("Id")
                        .HasName("pk_family_locations");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_family_locations_family_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_family_locations_location_id");

                    b.ToTable("family_locations");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeleteHash")
                        .HasColumnType("longtext")
                        .HasColumnName("delete_hash");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("MediaType")
                        .HasColumnType("int")
                        .HasColumnName("media_type");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("char(36)")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_family_media");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_family_media_family_id");

                    b.ToTable("family_media");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyUser", b =>
                {
                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("FamilyId", "UserId")
                        .HasName("pk_family_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_family_users_user_id");

                    b.ToTable("family_users");
                });

            modelBuilder.Entity("backend.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Accuracy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accuracy");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("location_type");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("backend.Domain.Entities.LocationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("link_type");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("char(36)")
                        .HasColumnName("location_id");

                    b.Property<string>("RefId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ref_id");

                    b.Property<int>("RefType")
                        .HasColumnType("int")
                        .HasColumnName("ref_type");

                    b.HasKey("Id")
                        .HasName("pk_location_links");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_location_links_location_id");

                    b.ToTable("location_links");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("FamilyMediaId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_media_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("RefId")
                        .HasColumnType("char(36)")
                        .HasColumnName("ref_id");

                    b.Property<int>("RefType")
                        .HasColumnType("int")
                        .HasColumnName("ref_type");

                    b.HasKey("Id")
                        .HasName("pk_media_links");

                    b.HasIndex("FamilyMediaId")
                        .HasDatabaseName("ix_media_links_family_media_id");

                    b.ToTable("media_links");
                });

            modelBuilder.Entity("backend.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Biography")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("biography");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_death");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<string>("FatherAvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("father_avatar_url");

                    b.Property<string>("FatherFullName")
                        .HasColumnType("longtext")
                        .HasColumnName("father_full_name");

                    b.Property<Guid?>("FatherId")
                        .HasColumnType("char(36)")
                        .HasColumnName("father_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("gender");

                    b.Property<string>("HusbandAvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("husband_avatar_url");

                    b.Property<string>("HusbandFullName")
                        .HasColumnType("longtext")
                        .HasColumnName("husband_full_name");

                    b.Property<Guid?>("HusbandId")
                        .HasColumnType("char(36)")
                        .HasColumnName("husband_id");

                    b.Property<bool>("IsDeceased")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deceased");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_root");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MotherAvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("mother_avatar_url");

                    b.Property<string>("MotherFullName")
                        .HasColumnType("longtext")
                        .HasColumnName("mother_full_name");

                    b.Property<Guid?>("MotherId")
                        .HasColumnType("char(36)")
                        .HasColumnName("mother_id");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nickname");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("occupation");

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("place_of_birth");

                    b.Property<string>("PlaceOfDeath")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("place_of_death");

                    b.Property<string>("WifeAvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("wife_avatar_url");

                    b.Property<string>("WifeFullName")
                        .HasColumnType("longtext")
                        .HasColumnName("wife_full_name");

                    b.Property<Guid?>("WifeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("wife_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_members_code");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_members_family_id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemberFace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bounding_box");

                    b.Property<double>("Confidence")
                        .HasColumnType("double")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("embedding");

                    b.Property<string>("Emotion")
                        .HasColumnType("longtext")
                        .HasColumnName("emotion");

                    b.Property<double>("EmotionConfidence")
                        .HasColumnType("double")
                        .HasColumnName("emotion_confidence");

                    b.Property<string>("FaceId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("face_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsVectorDbSynced")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_vector_db_synced");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<string>("OriginalImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("original_image_url");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("VectorDbId")
                        .HasColumnType("longtext")
                        .HasColumnName("vector_db_id");

                    b.HasKey("Id")
                        .HasName("pk_member_faces");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_member_faces_member_id");

                    b.ToTable("member_faces");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmotionalTag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emotional_tag");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<DateTime?>("HappenedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("happened_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_memory_items");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_memory_items_family_id");

                    b.ToTable("memory_items", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("MemoryItemId")
                        .HasColumnType("char(36)")
                        .HasColumnName("memory_item_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_memory_media");

                    b.HasIndex("MemoryItemId")
                        .HasDatabaseName("ix_memory_media_memory_item_id");

                    b.ToTable("memory_media", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryPerson", b =>
                {
                    b.Property<Guid>("MemoryItemId")
                        .HasColumnType("char(36)")
                        .HasColumnName("memory_item_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.HasKey("MemoryItemId", "MemberId")
                        .HasName("pk_memory_persons");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_memory_persons_member_id");

                    b.ToTable("memory_persons", (string)null);
                });

            modelBuilder.Entity("backend.Domain.Entities.PrivacyConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("PublicEventProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_event_properties");

                    b.Property<string>("PublicFamilyLocationProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_family_location_properties");

                    b.Property<string>("PublicFamilyProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_family_properties");

                    b.Property<string>("PublicFoundFaceProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_found_face_properties");

                    b.Property<string>("PublicMemberFaceProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_member_face_properties");

                    b.Property<string>("PublicMemberProperties")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("public_member_properties");

                    b.Property<string>("PublicMemoryItemProperties")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("public_memory_item_properties");

                    b.HasKey("Id")
                        .HasName("pk_privacy_configurations");

                    b.HasIndex("FamilyId")
                        .IsUnique()
                        .HasDatabaseName("ix_privacy_configurations_family_id");

                    b.ToTable("privacy_configurations");
                });

            modelBuilder.Entity("backend.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_prompts");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_prompts_code");

                    b.ToTable("prompts");
                });

            modelBuilder.Entity("backend.Domain.Entities.Relationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("char(36)")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<Guid>("SourceMemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("source_member_id");

                    b.Property<Guid>("TargetMemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("target_member_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_relationships_family_id");

                    b.HasIndex("SourceMemberId")
                        .HasDatabaseName("ix_relationships_source_member_id");

                    b.HasIndex("TargetMemberId")
                        .HasDatabaseName("ix_relationships_target_member_id");

                    b.ToTable("relationships");
                });

            modelBuilder.Entity("backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AuthProviderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("auth_provider_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("SubscriberId")
                        .HasColumnType("longtext")
                        .HasColumnName("subscriber_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AuthProviderId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth_provider_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Domain.Entities.UserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("action_type");

                    b.Property<string>("ActivitySummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("activity_summary");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid?>("GroupId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Metadata")
                        .HasColumnType("json")
                        .HasColumnName("metadata");

                    b.Property<string>("TargetId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("target_id");

                    b.Property<int>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("int")
                        .HasColumnName("target_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_activities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_activities_user_id");

                    b.ToTable("user_activities");
                });

            modelBuilder.Entity("backend.Domain.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Language")
                        .HasColumnType("int")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<int>("Theme")
                        .HasColumnType("int")
                        .HasColumnName("theme");

                    b.HasKey("UserId")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("backend.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("LastName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("phone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_profiles");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_external_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_profiles_user_id");

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("backend.Domain.Entities.VoiceGeneration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<double>("Duration")
                        .HasColumnType("double")
                        .HasColumnName("duration");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("text");

                    b.Property<Guid>("VoiceProfileId")
                        .HasColumnType("char(36)")
                        .HasColumnName("voice_profile_id");

                    b.HasKey("Id")
                        .HasName("pk_voice_generations");

                    b.HasIndex("VoiceProfileId")
                        .HasDatabaseName("ix_voice_generations_voice_profile_id");

                    b.ToTable("voice_generations");
                });

            modelBuilder.Entity("backend.Domain.Entities.VoiceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("audio_url");

                    b.Property<bool>("Consent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("consent");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_date");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("language");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("char(36)")
                        .HasColumnName("member_id");

                    b.Property<string>("OverallQuality")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("overall_quality");

                    b.Property<string>("QualityMessages")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("quality_messages");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double")
                        .HasColumnName("quality_score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_voice_profiles");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_voice_profiles_member_id");

                    b.ToTable("voice_profiles");
                });

            modelBuilder.Entity("backend.Domain.Entities.Event", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany("Events")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_events_families_family_id");

                    b.OwnsOne("backend.Domain.ValueObjects.LunarDate", "LunarDate", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("char(36)")
                                .HasColumnName("id");

                            b1.Property<int>("Day")
                                .HasColumnType("int")
                                .HasColumnName("day");

                            b1.Property<bool>("IsLeapMonth")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("is_leap_month");

                            b1.Property<int>("Month")
                                .HasColumnType("int")
                                .HasColumnName("month");

                            b1.HasKey("Id")
                                .HasName("pk_events");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("fk_events_events_id");
                        });

                    b.Navigation("Family");

                    b.Navigation("LunarDate");
                });

            modelBuilder.Entity("backend.Domain.Entities.EventMember", b =>
                {
                    b.HasOne("backend.Domain.Entities.Event", "Event")
                        .WithMany("EventMembers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_event_members_events_event_id");

                    b.HasOne("backend.Domain.Entities.Member", "Member")
                        .WithMany("EventMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_event_members_members_member_id");

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyLimitConfiguration", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithOne("FamilyLimitConfiguration")
                        .HasForeignKey("backend.Domain.Entities.FamilyLimitConfiguration", "FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_limit_configurations_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyLink", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family1")
                        .WithMany()
                        .HasForeignKey("Family1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_links_families_family1_id");

                    b.HasOne("backend.Domain.Entities.Family", "Family2")
                        .WithMany()
                        .HasForeignKey("Family2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_links_families_family2_id");

                    b.Navigation("Family1");

                    b.Navigation("Family2");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyLocation", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_locations_families_family_id");

                    b.HasOne("backend.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_locations_locations_location_id");

                    b.Navigation("Family");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyMedia", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_family_media_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyUser", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany("FamilyUsers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_users_families_family_id");

                    b.HasOne("backend.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_family_users_users_user_id");

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Entities.LocationLink", b =>
                {
                    b.HasOne("backend.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_links_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("backend.Domain.Entities.MediaLink", b =>
                {
                    b.HasOne("backend.Domain.Entities.FamilyMedia", "FamilyMedia")
                        .WithMany("MediaLinks")
                        .HasForeignKey("FamilyMediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_links_family_media_family_media_id");

                    b.Navigation("FamilyMedia");
                });

            modelBuilder.Entity("backend.Domain.Entities.Member", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_members_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemberFace", b =>
                {
                    b.HasOne("backend.Domain.Entities.Member", "Member")
                        .WithMany("MemberFaces")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_faces_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryItem", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_items_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryMedia", b =>
                {
                    b.HasOne("backend.Domain.Entities.MemoryItem", "MemoryItem")
                        .WithMany("MemoryMedia")
                        .HasForeignKey("MemoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_media_memory_items_memory_item_id");

                    b.Navigation("MemoryItem");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryPerson", b =>
                {
                    b.HasOne("backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memory_persons_members_member_id");

                    b.HasOne("backend.Domain.Entities.MemoryItem", "MemoryItem")
                        .WithMany("MemoryPersons")
                        .HasForeignKey("MemoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memory_persons_memory_items_memory_item_id");

                    b.Navigation("Member");

                    b.Navigation("MemoryItem");
                });

            modelBuilder.Entity("backend.Domain.Entities.PrivacyConfiguration", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithOne("PrivacyConfiguration")
                        .HasForeignKey("backend.Domain.Entities.PrivacyConfiguration", "FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_privacy_configurations_families_family_id");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("backend.Domain.Entities.Relationship", b =>
                {
                    b.HasOne("backend.Domain.Entities.Family", "Family")
                        .WithMany("Relationships")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationships_families_family_id");

                    b.HasOne("backend.Domain.Entities.Member", "SourceMember")
                        .WithMany("SourceRelationships")
                        .HasForeignKey("SourceMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationships_members_source_member_id");

                    b.HasOne("backend.Domain.Entities.Member", "TargetMember")
                        .WithMany("TargetRelationships")
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationships_members_target_member_id");

                    b.Navigation("Family");

                    b.Navigation("SourceMember");

                    b.Navigation("TargetMember");
                });

            modelBuilder.Entity("backend.Domain.Entities.UserActivity", b =>
                {
                    b.HasOne("backend.Domain.Entities.User", "User")
                        .WithMany("UserActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_activities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Entities.UserPreference", b =>
                {
                    b.HasOne("backend.Domain.Entities.User", "User")
                        .WithOne("Preference")
                        .HasForeignKey("backend.Domain.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("backend.Domain.Entities.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("backend.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Domain.Entities.VoiceGeneration", b =>
                {
                    b.HasOne("backend.Domain.Entities.VoiceProfile", "VoiceProfile")
                        .WithMany("VoiceGenerations")
                        .HasForeignKey("VoiceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voice_generations_voice_profiles_voice_profile_id");

                    b.Navigation("VoiceProfile");
                });

            modelBuilder.Entity("backend.Domain.Entities.VoiceProfile", b =>
                {
                    b.HasOne("backend.Domain.Entities.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voice_profiles_members_member_id");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("backend.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventMembers");
                });

            modelBuilder.Entity("backend.Domain.Entities.Family", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("FamilyLimitConfiguration");

                    b.Navigation("FamilyUsers");

                    b.Navigation("Members");

                    b.Navigation("PrivacyConfiguration");

                    b.Navigation("Relationships");
                });

            modelBuilder.Entity("backend.Domain.Entities.FamilyMedia", b =>
                {
                    b.Navigation("MediaLinks");
                });

            modelBuilder.Entity("backend.Domain.Entities.Member", b =>
                {
                    b.Navigation("EventMembers");

                    b.Navigation("MemberFaces");

                    b.Navigation("SourceRelationships");

                    b.Navigation("TargetRelationships");
                });

            modelBuilder.Entity("backend.Domain.Entities.MemoryItem", b =>
                {
                    b.Navigation("MemoryMedia");

                    b.Navigation("MemoryPersons");
                });

            modelBuilder.Entity("backend.Domain.Entities.User", b =>
                {
                    b.Navigation("Preference");

                    b.Navigation("Profile");

                    b.Navigation("UserActivities");
                });

            modelBuilder.Entity("backend.Domain.Entities.VoiceProfile", b =>
                {
                    b.Navigation("VoiceGenerations");
                });
#pragma warning restore 612, 618
        }
    }
}
