using backend.Application.AI.Common;
using backend.Application.Common.Interfaces;
using backend.Application.Common.Models;
using backend.Domain.Enums;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using backend.Application.Common.Models.AISettings;
using backend.Application.AI.ContentGenerators;

namespace backend.Infrastructure.AI.ContentGenerators
{
    public class LocalAIContentGenerator : IAIContentGenerator
    {
        private readonly ILogger<LocalAIContentGenerator> _logger;
        private readonly AIContentGeneratorSettings _aiContentGeneratorSettings;

        public AIProviderType ProviderType => AIProviderType.LocalAI;

        public LocalAIContentGenerator(ILogger<LocalAIContentGenerator> logger, IOptions<AIContentGeneratorSettings> aiContentGeneratorSettings)
        {
            _logger = logger;
            _aiContentGeneratorSettings = aiContentGeneratorSettings.Value;
        }

        public async Task<Result<AIResult>> GenerateContentAsync(AIRequest request, CancellationToken cancellationToken = default)
        {
            var localAISettings = _aiContentGeneratorSettings.Providers["LocalAI"] as LocalAISettings;
            if (localAISettings == null || string.IsNullOrEmpty(localAISettings.Endpoint))
            {
                return Result<AIResult>.Failure("LocalAI Endpoint is not configured.", "ConfigurationError");
            }

            // TODO: Implement actual call to LocalAI API
            _logger.LogInformation("Generating content with LocalAI for member {MemberId} and style {Style}.", request.MemberId, request.Style);

            // Simulate API call
            await Task.Delay(300, cancellationToken);

            var generatedContent = $"This is a simulated biography for member {request.MemberId} in {request.Style} style, generated by LocalAI. Prompt: {request.UserPrompt}";
            var tokensUsed = request.UserPrompt.Length / 5 + generatedContent.Length / 5; // Very rough token estimation

            return Result<AIResult>.Success(new AIResult
            {
                Content = generatedContent,
                TokensUsed = tokensUsed,
                Provider = AIProviderType.LocalAI,
                GeneratedAt = DateTime.UtcNow
            });
        }
    }
}
