using backend.Application.AI.Common;
using backend.Application.Common.Interfaces;
using backend.Application.Common.Models;
using backend.Domain.Enums;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using backend.Application.Common.Models.AISettings;
using backend.Application.AI.ContentGenerators;

namespace backend.Infrastructure.AI.ContentGenerators
{
    public class OpenAIAIContentGenerator : IAIContentGenerator
    {
        private readonly ILogger<OpenAIAIContentGenerator> _logger;
        private readonly AIContentGeneratorSettings _aiContentGeneratorSettings;

        public AIProviderType ProviderType => AIProviderType.OpenAI;

        public OpenAIAIContentGenerator(ILogger<OpenAIAIContentGenerator> logger, IOptions<AIContentGeneratorSettings> aiContentGeneratorSettings)
        {
            _logger = logger;
            _aiContentGeneratorSettings = aiContentGeneratorSettings.Value;
        }

        public async Task<Result<AIResult>> GenerateContentAsync(AIRequest request, CancellationToken cancellationToken = default)
        {
            var openAISettings = _aiContentGeneratorSettings.Providers["OpenAI"] as OpenAISettings;
            if (openAISettings == null || string.IsNullOrEmpty(openAISettings.ApiKey))
            {
                return Result<AIResult>.Failure("OpenAI API Key is not configured.", "ConfigurationError");
            }

            // TODO: Implement actual call to OpenAI API
            _logger.LogInformation("Generating content with OpenAI for member {MemberId} and style {Style}.", request.MemberId, request.Style);

            // Simulate API call
            await Task.Delay(700, cancellationToken);

            var generatedContent = $"This is a simulated biography for member {request.MemberId} in {request.Style} style, generated by OpenAI. Prompt: {request.UserPrompt}";
            var tokensUsed = request.UserPrompt.Length / 3 + generatedContent.Length / 3; // Very rough token estimation

            return Result<AIResult>.Success(new AIResult
            {
                Content = generatedContent,
                TokensUsed = tokensUsed,
                Provider = AIProviderType.OpenAI,
                GeneratedAt = DateTime.UtcNow
            });
        }
    }
}
